name: Scheduled Up
on:
  schedule:
    - cron: "0 0,6,12 * * *"
  workflow_dispatch:
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Scheduled Up
        run: curl https://posts-upper.vercel.app/api/up
